title: Krishnaveni Peesapati
logo: https://github.com/Krishna061992/MY_Portfolio/blob/main/GitHub%20Image%20Resized.jpg?raw=true



description: Data Scientist 
show_downloads: true
theme: jekyll-theme-minimal
